# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  uipath

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'VariantMatrix'